services:
  api:
    build:
      context: .
      dockerfile: ./docker/gpu/Dockerfile
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
